#!/usr/bin/env python3

import sys
import os

#variable for any pcap file 
file_name = sys.argv[1]

#parse all src ips sort and count them
cmd = 'tshark -r ' + str(file_name) + ' -Y tcp -T fields -e ip.src | sort | uniq -c'
#parse all dst ips sort and count them
cmd2 = 'tshark -r ' + str(file_name) + ' -Y tcp -T fields -e ip.dst | sort | uniq -c'

#print a space to separate headers
print("                     ")
print("tshark src ips by count")
print("---------------------")
#call tshark shell command(2)
os.system(cmd)

#print a space to separate headers
print("                     ")
print("tshark dst ips by count")
print("---------------------")
#call tshark shell command(2)
os.system(cmd2)
